name: sendbird_chat_sdk
description: With Sendbird Chat for Flutter, you can easily build an in-app chat with all the essential messaging features.
version: 4.8.0
homepage: https://sendbird.com
repository: https://github.com/sendbird/sendbird-chat-sdk-flutter
documentation: https://sendbird.com/docs/chat/sdk/v4/flutter/getting-started/send-first-message

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

platforms:
  android:
  ios:
  web:

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  encrypt: ^5.0.3
  shared_preferences: ^2.3.4
  http: ^1.2.2
  logger: ^2.5.0
  mime: ^2.0.0
  connectivity_plus: ^6.1.1
  http_parser: ^4.0.2
  web_socket_channel: ^3.0.1
  universal_io: ^2.2.2
  async: ^2.11.0
  path_provider: ^2.1.5
  path: ^1.9.0
  isar_community: ^3.3.0-dev.1
  isar_community_flutter_libs: ^3.3.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.7
  stack_trace: ^1.11.1
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  isar_community_generator: ^3.3.0-dev.1
